[env]
TERM = "screen-256color"

[font]
size = 13

[font.normal]
family = "Google Sans Code"
# family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[window]
# opacity = 0.94
option_as_alt = "both"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[colors.primary]
# background = "#000000"

[general]
import = ["~/.config/alacritty/themes/bloodmoon.toml"]
# import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]
# import = ["~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]
live_config_reload = true
