[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1.0
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 0
y = 0
